- Jenkinsfile
Use Drizzlepac's Jenkinsfile as starter for this package.
> Copy Drizzlepac Jenkinsfile

- setup.py
> Fix typo residue: stsci-hack->spacetelescope

- Jenkinsfile
- MANIFEST.in
- hlapipeline/align_to_gaia.py
- setup.py
- tests/base_classes.py
- tests/base_test.py
- tests/test_align.py
Update Jenkinsfile to (hopefully) correctly use Artifactory.
> Initial attempt to add BIGDATA to Jenkinsfile

- Jenkinsfile
- tests/test_align.py
This PR corrects the typo identified in the code review for PR #3 while also revising the code to be more consistent in what should be a class variable (input_loc) and what can be an input parameter (input_filenames).
> Address code review for PR#3

- tests/base_test.py
- tests/test_align.py
Create a new function run_align that contains the steps needed to update files and run alignment for them.   It returns a table with the output results.
> added run_align method to BaseHLATest

- hlapipeline/utils/catalog_utils.py
The function, randomSelectFromCSV, allows the user to specify the desired number of entries to obtain from a comma-separated values (CSV) file which contains data extracted from the STScI archive for ACS, WFC3, and WFPC2 instruments. The entries from the input table are chosen at random with no duplication, and returned as an Astropy table.
> Function to extract random entries (lines) from a CSV file

- tests/test_align.py
Updated the test_align.py to include a new test, `test_align_randomFields`, and a new support function, `get_dataset_list`.  This is a WIP, but the functionality currently works.  Need to (at least):
- allow input of CSV file and/or allow input of master CSV file which then can be processed with the utility function `randomSelectFromCSV`
- capture output potentially in a selective manner versus ">& output.log"
> [WIP] Created test to process a random list of datasets

- tests/test_align.py
Addresses JIRA HLA-76
Capture exception information (type, value, traceback) for diagnostic purposes for each dataset processed in the "random 100 datasets" tests.
> Capture the exceptions for diagnostic purposes

- tests/test_align.py
Added a marker and timestamp to the test output log for diagnostic purposes.
> Jira hla 76

- hlapipeline/utils/astroquery_utils.py
Fixes Git Issue #24.
The updated astroquery_utils.py, retrieve_observation(), code checks the table returned from MAST after filtering the entries to obtain FLC images.  If the table is empty, a new filtering is done to capture FLT images instead.  Some datasets properly do not have any FLC images.  If there are neither FLC nor FLT images, the code generates informational messages.  The high-level calling code will eventually throw an exception in this test environment.
> If no FLCs available, retrieve FLTs instead.

- hlapipeline/utils/astrometric_utils.py
Re-implement new default catalog originally pushed in #26 and accidentally backed out in #27.
> Re-apply new catalog default

- docs/design.rst
- docs/index.rst
This adds an initial design document to the docs for this package, with working design for the image alignment processing.
> Initial version of design docs

- README.rst
A quick description of how to (best?) run the tests associated with this package has been added to the README.
> Update readme tests

- hlapipeline/utils/filter.py
The filter.py contains the function analyze_data opens the input FITS file to access the primary header data.  Based upon the values of certain FITS keywords, the function determines whether or not this dataset can be reconciled against an astrometric  catalog and, for multiple images, used to create a mosaic.
> [WIP] Function to filter datasets to determine viability for processing

- hlapipeline/alignimages.py
This update simplifies the logic in the 'check_and_get_data' function in alignimages, while also correcting a bug that was present in the original implementation.  
Originally, if the local file could not be found (glob returned nothing), then it tried to open the file using fits.open, even though it did not exist.  This logic has been replaced with what I believe is more general logic that should still work equally as well.
> Simplified and corrected logic in get_and_check_data

- hlapipeline/alignimages.py
- tests/test_random.py
Created new test for processing 100 random datasets (50 each for ACS and WFC3) using the new algorithms derived for the on-going HLA project.  The new test addresses a portion of JIRA-HLA-128.
> Created test for random datasets using new HLA algorithms

- hlapipeline/utils/astrometric_utils.py
This simple fix should eliminate the problems we are having with missing magnitudes from the astrometric catalogs.
> Ignore magnitudes from astrometric catalog

- hlapipeline/utils/filter.py
Checking FGSLOCK and CHINJECT for additional evaluation of input data.  Extended table to hold more information for evaluation.
> Check additional keywords for evaluation and minor improvements.

- hlapipeline/alignimages.py
- hlapipeline/utils/astrometric_utils.py
This revision adds code which computes separate RMS values for RA and DEC for reporting in the headerlet.  The computations are based on the same astropy coordinates computations used to compute the FIT_RMS.
In addition,
- printing out the git information is made optional, and controlled through a new parameter
- deleted an unused variable (numcatalogs)
> Add code to compute RMS_RA, RMS_DEC

- hlapipeline/alignimages.py
- hlapipeline/utils/catalog_utils.py
- hlapipeline/utils/filter.py
- tests/test_bigRandom.py
Updates to populate properly the filterTable.
> From master special big test

- hlapipeline/alignimages.py
Testing uncovered cases where using a different matching algorithm resulted in a valid fit (albeit with >10mas rms), yet those solutions were NOT getting into the filteredTable results.   It was uncovered that the `match_2dhist_fit` function was copying `meta` into `best_meta` blindly resulting in those other computations being overwritten.  
In addition, the logic for managing `imglist` and the metadata attributes `meta` and `best_meta` was overly complicated.  These changes create the `imglist` outside of the iterations over catalogs and matching functions since that information is constant for all those iterations.  
Finally, a small tweak includes the TOTAL processing time at the very end.
> Fixed best_meta logic, simplified best_meta updates

- hlapipeline/alignimages.py
Mike and Michele fixed the logic in the current version of the code so once a best fit solution is found (best_fit_rms<MAX_FIT_RMS, where MAX_FIT_RMS=10), the search is over.
> Fix to break out of two for loops when fix solution < MAX_FIT_RMS

- Jenkinsfile
- setup.py
Removing unused pyyaml dependency to fix conda build failures.
> Removed unused pyyaml

- hlapipeline/alignimages.py
The matching/fitting algorithm invocation and the subsequent best_rms_xxx updates are now in a "try" block.  The "except" block sets the status in the filteredTable to "bad", but the looping is allowed to continue in the hope the next possible iteration (i.e., different match algorithm, or different astrometric catalog, or both) can find a viable solution.  The most important point is the exception is caught and handled so the alignimages ends gracefully.
> Implemented try/except around matching functionality.

- hlapipeline/utils/astrometric_utils.py
Very crowded fields of view (such as jc3c02b5q_flc.fits in OmegaCen) can cause the background estimation step in creating the source catalog to throw an Exception.  This change iterates over a limited set of parameter values to try to find something that will work.  It does allow (in combination with #70) crowded fields to actually generate usable source catalogs, at least in initial testing.
> Fix Exceptions in background estimation
